[package]
name = "abe-sss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek-ng = "4.1.1"
rand_core = "0.6.3"
chacha20poly1305 = "0.9.0"